FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

MAINTAINER sergei <sergei.0910@gmail.com>

WORKDIR /root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        build-essential \
        curl \
        vim \
        git \
        net-tools \
        iputils-ping \
        netcat \
        tcpdump \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python \
        python-dev \
        python-numpy \
        python-wheel \
        python-mock \
        rsync \
        zip \
        unzip \
        g++ \
        mlocate \
        && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/* && \
        updatedb

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip --no-cache-dir install \
        ipykernel \
        jupyter \
        Cython==0.25.2 \
        matplotlib==2.0.2 \
        pandas==0.20.2 \
        h5py==2.6.0 \
        sgf==0.5 \
        futures==3.0.5 \
        python-jsonrpc==0.10.0 \
        tqdm \
        jedi \
        flake8 \
        autopep8 \
        && \
    python -m ipykernel.kernelspec

# Copy cuDNN
COPY cudnn/cudnn-8.0-linux-x64-v6.0.solitairetheme8 /tmp/

RUN tar xzf /tmp/cudnn-8.0-linux-x64-v6.0.solitairetheme8 && \
    cp -a cuda/include/* /usr/local/cuda/include/ && \
    cp -a cuda/lib64/* /usr/local/cuda/lib64/

RUN pip --no-cache-dir install \
    https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.3.0-cp27-none-linux_x86_64.whl 

# For CUDA profiling, TensorFlow requires CUPTI.
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

"""
# Java and bazel
    7  add-apt-repository ppa:webupd8team/java
   10  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
   11  apt-get update
   12  apt-get install -y oracle-java8-installer
   13  java -version
   22  wget https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-installer-linux-x86_64.sh
   24  chmod +x bazel-0.4.5-installer-linux-x86_64.sh
   25  ./bazel-0.4.5-installer-linux-x86_64.sh
   26  bazel version

# build tensorflow
   83  bazel clean
   84  ./configure
   85  bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-msse4.1 --copt=-msse4.2 --copt=-mfma --config=cuda //tensorflow/tools/pip_package:build_pip_package
   87  bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
   89  pip uninstall tensorflow-tensorboard
   92  pip uninstall tensorflow-gpu
   94  pip install /tmp/tensorflow_pkg/tensorflow-1.3.0-cp27-cp27mu-linux_x86_64.whl
"""

RUN git config --global user.name "hiropppe"
RUN git config --global user.email "sergei.0910@gmail.com"
