FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04

MAINTAINER sergei <sergei.0910@gmail.com>

WORKDIR /root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        build-essential \
        curl \
        vim \
        git \
        net-tools \
        iputils-ping \
        netcat \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python \
        python-dev \
        python-numpy \
        python-wheel \
        python-mock \
        rsync \
        zip \
        unzip \
        g++ \
        zlib1g-dev \
        luarocks \
        && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip --no-cache-dir install \
        ipykernel \
        jupyter \
        Cython==0.24 \
        matplotlib==2.0.2 \
        scipy==0.18.1 \
        pandas==0.20.2 \
        h5py==2.6.0 \
        sgf==0.5 \
        futures==3.0.5 \
        keras==1.2.0 \
        python-jsonrpc==0.10.0 \
        && \
    python -m ipykernel.kernelspec

WORKDIR /root

# Copy cuDNN
COPY cudnn/cudnn-8.0-linux-x64-v5.1.solitairetheme8 /tmp/

RUN tar xzf /tmp/cudnn-8.0-linux-x64-v5.1.solitairetheme8 && \
    cp -a cuda/include/* /usr/local/cuda/include/ && \
    cp -a cuda/lib64/* /usr/local/cuda/lib64/

RUN pip --no-cache-dir install \
    http://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp27-none-linux_x86_64.whl

# For CUDA profiling, TensorFlow requires CUPTI.
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

# todo 
#    4  git clone https://github.com/facebookresearch/darkforestGo.git
#    6  cd darkforestGo/
#    8  mkdir ~/lib
#   10  curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash
#   11  git clone https://github.com/torch/distro.git ~/lib/torch --recursive
#   12  cd ~/lib/torch; ./install.sh
#   13  luarocks install class
#   14  source ~/.bashrc
#   15  th
#   16  apt-get install luarocks
#   18  luarocks install class
#   19  luarocks install image
#   20  luarocks install tds
#   21  luarocks install cudnn
#   24  cd darkforestGo/
#   25  sh ./compile.sh
#   26  mkdir ./models
#   27  cd models/
#   28  wget https://www.dropbox.com/sh/6nm8g8z163omb9f/AAAOsp9WzSQrITY9veSmOA1pa/df1.bin?dl=0 -O df1.bin
#   29  wget https://www.dropbox.com/sh/6nm8g8z163omb9f/AACZwAeb0OOCReoeIWPRgILta/df2.bin?dl=0 -O df2.bin
#   30  wget https://www.dropbox.com/sh/6nm8g8z163omb9f/AABrO3wRZ5hLOk70gmu3rK7Ja/LICENSE?dl=0 -O LICENSE
#   31  wget https://www.dropbox.com/sh/6nm8g8z163omb9f/AABcYJKMOl6-Uol98boGa7n5a/playout-model.bin?dl=0 -O playout-model.bin
#   34  cd ../local_evaluator/
#   36  mkdir -p /data/local/go
#   37  chmod 666 /data/local/go
#   38  sh cnn_evaluator.sh 1 /data/local/go
#   40  cd ../cnnPlayerV2/
#   43  th cnnPlayerMCTSV2.lua --num_gpu 1 --time_limit 10

#   55  add-apt-repository ppa:webupd8team/java
#   56  apt-get update
#   57  apt-get install oracle-java8-installer
#   58  java -version
#   60  wget http://downloads.sourceforge.net/project/gogui/gogui/1.4.9/gogui-1.4.9.zip
#   62  unzip gogui-1.4.9.zip
#   75  git clone https://github.com/hiropppe/bambooStone.git
#   77  cd bambooStone/
#   79  git branch -a
#   80  git checkout parallel_mcts
#   81  git branch -a
#   86  pip install Cython==0.24
#   87  python setup.py build_ext -b .
#   98  pip install python-jsonrpc==0.10.0
#  101  python bbrpc -M params/policy/policy.json -W params/policy/weights.00088.hdf5 -Wr params/rollout/sample.hdf5 -mt params/rollout/mt_rands.txt -x33 params/rollout/x33.csv -d12 params/rollout/d12.csv

# /root/gogui-1.4.9/bin/gogui-twogtp -black "python /root/bambooStone/bbs --time-limit 10 --playout-limit 100000" -white "th cnnPlayerMCTSV2.lua --num_gpu 1 --time_limit 10" -games 3 -sgffile bbs_vs_darkforest -komi 7.5 -auto -force -verbose

